import {expect,it} from 'vitest'
import {hash,type SyncHead,type SyncNote} from '../server/knowledge/sync-contract'
import {syncOnce,type SyncState,type VaultAdapter} from './engine'
import type {SyncRemote} from './transport'
const n=(path:string,content:string):SyncNote=>({path,content,version:hash(content)})
const fixture=()=>{
 let head:SyncHead={revision:1,generation:'11111111-1111-4111-8111-111111111111',vaultId:'a'.repeat(64)}
 let notes=[n('A.md','original')];const history=new Map([[head.generation!,{head,notes}]]);let publishes=0,lost=false
 const remote:SyncRemote={head:async()=>head,manifest:async h=>{const s=history.get(h.generation!);if(!s)throw Object.assign(new Error('missing'),{status:404});return {head:s.head,notes:s.notes.map(({path,version})=>({path,version})),total:s.notes.length,nextCursor:null}},read:async(h,p)=>history.get(h.generation!)!.notes.find(n=>n.path===p)!,publish:async(expected,next,generation,vaultId)=>{
  if(expected.revision!==head.revision)throw Object.assign(new Error('cas'),{status:409});publishes++;head={revision:head.revision+1,generation,vaultId};notes=next;history.set(generation,{head,notes});if(lost){lost=false;throw new Error('timeout')}return head
 }}
 const device=()=>{let state:SyncState|null=null;let local:SyncNote[]=[];let crash=false
 const vault:VaultAdapter={list:async()=>new Map(local.map(n=>[n.path,n])),loadState:async()=>state,saveState:async s=>{state=structuredClone(s)},apply:async(before,target)=>{
  if(crash){crash=false;local=[...target.values()];throw new Error('interrupted')}
  expect([...before.values()]).toEqual(local);local=[...target.values()]
 },preserveConflicts:async()=>{}}
 return {vault,get state(){return state},get notes(){return local},set notes(n:SyncNote[]){local=n},set crash(v:boolean){crash=v}}
 }
 return {remote,device,get publishes(){return publishes},get notes(){return notes},set lost(v:boolean){lost=v}}
}
it('first empty vault downloads without publishing',async()=>{const f=fixture(),a=f.device();await syncOnce(f.remote,a.vault);expect(a.notes).toEqual([n('A.md','original')]);expect(f.publishes).toBe(0);expect(a.state?.baseline).toEqual([n('A.md','original')])})
it('first download preserves unrelated local notes',async()=>{const f=fixture(),a=f.device();a.notes=[n('L.md','mine')];await syncOnce(f.remote,a.vault);expect(a.notes).toHaveLength(2);expect(f.publishes).toBe(0)})
it('two devices editing different notes converge',async()=>{const f=fixture(),a=f.device(),b=f.device();await syncOnce(f.remote,a.vault);await syncOnce(f.remote,b.vault);a.notes.push(n('New.md','A'));await syncOnce(f.remote,a.vault);b.notes=[n('A.md','B')];await syncOnce(f.remote,b.vault);await syncOnce(f.remote,a.vault);expect(a.notes.map(n=>n.content).sort()).toEqual(['A','B']);expect(b.notes.map(n=>n.content).sort()).toEqual(['A','B'])})
it('two divergent edits pause publishing and preserve both versions',async()=>{const f=fixture(),a=f.device(),b=f.device();await syncOnce(f.remote,a.vault);await syncOnce(f.remote,b.vault);a.notes=[n('A.md','A')];b.notes=[n('A.md','B')];await syncOnce(f.remote,a.vault);const r=await syncOnce(f.remote,b.vault);expect(r.status).toBe('conflict');expect(b.notes[0].content).toBe('B');expect(b.state?.conflicts[0].remote?.content).toBe('A');expect(f.publishes).toBe(1)})
it('lost publication response is reconciled without publishing twice',async()=>{const f=fixture(),a=f.device();await syncOnce(f.remote,a.vault);a.notes=[n('A.md','edit')];f.lost=true;await expect(syncOnce(f.remote,a.vault)).rejects.toThrow();await syncOnce(f.remote,a.vault);expect(f.publishes).toBe(1);expect(a.state?.pending).toBeNull()})
it('interrupted local apply resumes from the journal',async()=>{const f=fixture(),a=f.device();a.crash=true;await expect(syncOnce(f.remote,a.vault)).rejects.toThrow();await syncOnce(f.remote,a.vault);expect(a.notes).toEqual([n('A.md','original')]);expect(f.publishes).toBe(0)})
it('user edits after interrupted apply are retained',async()=>{const f=fixture(),a=f.device();a.crash=true;await expect(syncOnce(f.remote,a.vault)).rejects.toThrow();a.notes=[n('A.md','mine')];await syncOnce(f.remote,a.vault);expect(a.notes[0].content).toBe('mine')})
it('an offline first download cannot establish a baseline',async()=>{const f=fixture(),a=f.device();f.remote.read=async()=>{throw Error('offline')};await expect(syncOnce(f.remote,a.vault)).rejects.toThrow();expect(a.state).toBeNull();expect(a.notes).toEqual([])})
it('CAS retries stop after three failures without changing the baseline',async()=>{const f=fixture(),a=f.device();await syncOnce(f.remote,a.vault);a.notes=[n('A.md','edit')];let attempts=0;f.remote.publish=async()=>{attempts++;throw Object.assign(new Error('cas'),{status:409})};await expect(syncOnce(f.remote,a.vault)).rejects.toThrow();expect(attempts).toBe(3);expect(a.state?.baseline).toEqual([n('A.md','original')]);expect(a.notes[0].content).toBe('edit')})
it('lost response followed by another device publishing preserves both updates',async()=>{const f=fixture(),a=f.device(),b=f.device();await syncOnce(f.remote,a.vault);await syncOnce(f.remote,b.vault);a.notes=[n('A.md','edit')];f.lost=true;await expect(syncOnce(f.remote,a.vault)).rejects.toThrow();b.notes.push(n('B.md','second'));await syncOnce(f.remote,b.vault);await syncOnce(f.remote,a.vault);await syncOnce(f.remote,a.vault);expect(a.notes.map(n=>n.content).sort()).toEqual(['edit','second']);expect(f.publishes).toBe(2)})
it('retries a stale publication against a newly published snapshot',async()=>{const f=fixture(),a=f.device();await syncOnce(f.remote,a.vault);a.notes.push(n('L.md','local'));const publish=f.remote.publish;let race=true;f.remote.publish=async(...args)=>{if(race){race=false;await publish(args[0],[n('A.md','original'),n('R.md','remote')],'44444444-4444-4444-8444-444444444444',args[3]);throw Object.assign(new Error('cas'),{status:409})}return publish(...args)};await syncOnce(f.remote,a.vault);expect(a.notes.map(n=>n.path).sort()).toEqual(['A.md','L.md','R.md'])})
it('recovers an application interrupted after only some files were written',async()=>{const f=fixture(),a=f.device();a.notes=[n('L.md','local')];const apply=a.vault.apply;let first=true;a.vault.apply=async(before,target)=>{if(first){first=false;a.notes=[...target.values()].slice(0,1);throw Error('partial')}await apply(before,target)};await expect(syncOnce(f.remote,a.vault)).rejects.toThrow();await syncOnce(f.remote,a.vault);expect(a.notes.map(n=>n.path).sort()).toEqual(['A.md','L.md'])})
