import { afterEach, expect, it, vi } from 'vitest';
import { createCompanyNotesHandler } from '../../../server/company-notes';
const id = '11111111-1111-4111-8111-111111111111';
const token = 'owner-token-'.repeat(4);
const stored = { id, market: 'cn', code: '600900', title: '长江电力', content: '# 分析', revision: 1, created_at: '2026-10-09T00:00:00Z', updated_at: '2026-10-09T00:00:00Z' };
function response() { return { code: 0, body: null as any, headers: {} as Record<string, string>, setHeader(k: string, v: string) { this.headers[k] = v; }, status(n: number) { this.code = n; return this; }, json(b: unknown) { this.body = b; return b; } }; }
function setup(result: unknown = [stored], configured = token) { const db = vi.fn(async () => result); return { db, handler: createCompanyNotesHandler(() => db, () => configured) }; }
afterEach(() => vi.restoreAllMocks());
it('public list excludes content and works without a write token', async () => { const { handler } = setup([stored], ''); const res = response(); await handler({ method: 'GET', headers: {}, query: { action: 'list', market: 'cn', code: '600900' } }, res); expect(res.code).toBe(200); expect(res.body.items[0]).toMatchObject({ id, title: '长江电力', updatedAt: stored.updated_at }); expect(res.body.items[0]).not.toHaveProperty('content'); expect(res.body.hasMore).toBe(false); });
it('public full note can be read without authentication', async () => { const { handler } = setup(); const res = response(); await handler({ method: 'GET', headers: {}, query: { action: 'note', id } }, res); expect(res.code).toBe(200); expect(res.body.content).toBe('# 分析'); });
it.each(['create', 'update', 'unlock'])('rejects unauthenticated %s before accessing database', async (action) => { const { handler, db } = setup(); const res = response(); await handler({ method: 'POST', headers: {}, query: { action }, body: stored }, res); expect(res.code).toBe(401); expect(db).not.toHaveBeenCalled(); });
it('valid token unlocks without querying database', async () => { const { handler, db } = setup(); const res = response(); await handler({ method: 'POST', headers: { authorization: `Bearer ${token}` }, query: { action: 'unlock' } }, res); expect(res.code).toBe(200); expect(res.body).toEqual({ ok: true }); expect(db).not.toHaveBeenCalled(); });
it('authorized create returns saved note with revision', async () => { const { handler, db } = setup({ status: 'ok', note: stored }); const res = response(); await handler({ method: 'POST', headers: { authorization: `Bearer ${token}` }, query: { action: 'create' }, body: { id, market: 'cn', code: '600900', title: '长江电力', content: '# 分析' } }, res); expect(res.code).toBe(200); expect(res.body).toMatchObject({ id, content: '# 分析', revision: 1 }); expect(db.mock.calls[0]).toEqual(['rpc/businessweb_create_company_note', 'POST', { note_id: id, note_market: 'cn', note_code: '600900', note_title: '长江电力', note_content: '# 分析' }]); });
it('conflicting update returns 409', async () => { const { handler } = setup({ status: 'conflict' }); const res = response(); await handler({ method: 'POST', headers: { authorization: `Bearer ${token}` }, query: { action: 'update' }, body: { id, expectedRevision: 1, title: '新判断', content: '正文' } }, res); expect(res.code).toBe(409); });
it('missing note returns 404', async () => { const { handler } = setup([]); const res = response(); await handler({ method: 'GET', headers: {}, query: { action: 'note', id } }, res); expect(res.code).toBe(404); });
it.each([{ title: ' ', content: 'x' }, { title: 'x', content: '' }, { title: 'x', content: '中'.repeat(350000) }])('rejects empty or oversized notes', async (fields) => { const { handler, db } = setup(); const res = response(); await handler({ method: 'POST', headers: { authorization: `Bearer ${token}` }, query: { action: 'create' }, body: { id, market: 'cn', code: '600900', ...fields } }, res); expect([400, 413]).toContain(res.code); expect(db).not.toHaveBeenCalled(); });
it.each([{ action: 'list', market: 'cn', code: '600900', offset: '-1' }, { action: 'list', market: 'wrong', code: 'a' }, { action: 'note', id: '../private' }, { action: 'unknown' }])('rejects invalid query', async (query) => { const { handler, db } = setup(); const res = response(); await handler({ method: 'GET', headers: {}, query }, res); expect([400, 404]).toContain(res.code); expect(db).not.toHaveBeenCalled(); });
it('write actions reject GET', async () => { const { handler } = setup(); const res = response(); await handler({ method: 'GET', headers: { authorization: `Bearer ${token}` }, query: { action: 'create' } }, res); expect(res.code).toBe(405); });
it('missing write configuration reports 503', async () => { const { handler } = setup([], ''); const res = response(); await handler({ method: 'POST', headers: {}, query: { action: 'unlock' } }, res); expect(res.code).toBe(503); });
it('list paginates 50 notes', async () => { const { handler } = setup(Array.from({ length: 51 }, (_, i) => ({ ...stored, id: String(i) }))); const res = response(); await handler({ method: 'GET', headers: {}, query: { action: 'list', market: 'cn', code: '600900' } }, res); expect(res.body.items).toHaveLength(50); expect(res.body.hasMore).toBe(true); });
it('disallowed origin cannot write', async () => { const { handler, db } = setup(); const res = response(); await handler({ method: 'POST', headers: { origin: 'https://evil.example', authorization: `Bearer ${token}` }, query: { action: 'unlock' } }, res); expect(res.code).toBe(403); expect(db).not.toHaveBeenCalled(); });
